application: cfotmwod
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /touch
  static_dir: touch

- url: /css
  static_dir: touch/resources/css

- url: /js
  static_dir: public/js

- url: .*
  script: cfotmwod.app

skip_files:
- ^(.*/)?README\.md
- ^(.*/).*\.pyc
